<div style="background-color:<?php echo $this->bcolor;?>" class="picture-output" id="picture-<?php echo $this->id;?>">
    <h2>Picture - <?php echo $this->title; ?> - <?php echo $this->id; ?></h2>
    <?php if ($this->loggedIn == true): ?>
	    <div id='topic-toolbar-edit' class='toolbar-tab'><a href="/picture/edit?id=<?php echo $this->id; ?>&from=correspondant">Edit</a></div>
    <?php endif; ?>
    <div class="picture-item-caption">
        <span><?php echo $this->caption;?></span>
	<br />
        <span><?php echo $this->original;?></span>
    </div>
    <div onclick="clickPictureItem('picture-<?php echo $this->id;?>')">
    	<span><img src="<?php echo $this->picture; ?>" width=¨100¨ height=¨100¨></span>
    </div>
</div>
