<?php
	$topic = "wordage";
?>
<div class="wordage-item" id="wordage-<?php echo $this->id;?>">
    <div class="lines">
        <h2>Wordage - <?php echo $this->title; ?> - <?php echo $this->id; ?></h2>
	<div id="wordage-username" class="small_letters"><?php echo $this->original; ?></div>
	<div id="wordage-timestamp" class="small_letters"><?php echo $this->username; ?></div>
	<?php if ($this->loggedIn == true): ?>
	    <div id='topic-toolbar-edit' class='toolbar-tab'><a href="/wordage/edit?id=<?php echo $this->id; ?>&from=correspondant">Edit</a></div>
	<?php endif; ?>
        <div class="wordage-item-title">
	    <br />
            <span><?php echo $this->original;?></span>
        </div>
	<div id="wordage-edit" class="wordage-item-content">
		<div id="wordage-edit-textarea">
		    <?php echo $this->wordage; ?>
		</div>
	</div>
	<div id="wordage-view" class="wordage-item-content">
		<?php echo $this->wordage; ?>
	</div>
	<div id="wordage-target-<?php echo $id; ?>">
	</div>
        <div class="holes hole-top"></div>
        <div class="holes hole-middle"></div>
        <div class="holes hole-bottom"></div>
    </div>
</div>
