<div id="signup_box" class="pulldown_form">
	<div id="close_box" class="far_right"><a href="#" onclick="closeBox()">X</a></div>
<?php
/*
$this->headTitle('User Registration - Step 1 - Login and Password');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'User Registration' => $this->url('registration')
            ]);

*/
$form->get('username')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'myhandle'
    ]);

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'name@yourcompany.com'
    ]);

$form->get('first_name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'John'
    ]);

$form->get('middle_i')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'B.'
    ]);

$form->get('last_name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Doe'
    ]);

$form->get('passphrase')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'secret passphrase',
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Type password here (6 characters at minimum)'
    ]);

$form->get('confirm_password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Repeat password'
    ]);

$form->get('submit')->setAttributes(array('class'=>'btn btn-primary'));

$form->prepare();
?>

<h1>User Registration</h1>

<?php
$messages = $this->messages;

if (array_key_exists('email',$messages))
{
	$email_messages = $messages['email'];
}
else
{
	$email_messages = Array();
}
if (array_key_exists('username_taken',$messages))
{
        $username_taken_message = $messages['username_taken'];
}
else
{
	$username_taken_message = "Username Valid";
}
?>
<div>
<?php print($username_taken_message) ?>
</div>


<?= $this->form()->openTag($form); ?>
    <div class="row">
        
            <?= $this->formLabel($form->get('username')); ?>
            <?= $this->formElement($form->get('username')); ?>
            <?= $this->formElementErrors($form->get('username')); ?>                              
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>                              
    </div>
    <div class="row">
        
            <?= $this->formLabel($form->get('first_name')); ?>
            <?= $this->formElement($form->get('first_name')); ?>
            <?= $this->formElementErrors($form->get('first_name')); ?>                              
            <?= $this->formLabel($form->get('middle_i')); ?>
            <?= $this->formElement($form->get('middle_i')); ?>
            <?= $this->formElementErrors($form->get('middle_i')); ?>                              

    </div>
    <div class="row">

            <?= $this->formLabel($form->get('last_name')); ?>
            <?= $this->formElement($form->get('last_name')); ?>
            <?= $this->formElementErrors($form->get('last_name')); ?>                              
            <?= $this->formLabel($form->get('passphrase')); ?>
            <?= $this->formElement($form->get('passphrase')); ?>
            <?= $this->formElementErrors($form->get('passphrase')); ?>                              
    </div>
    <div class="row">

            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <?= $this->formElementErrors($form->get('password')); ?>                              
            <?= $this->formLabel($form->get('confirm_password')); ?>
            <?= $this->formElement($form->get('confirm_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_password')); ?>                              
    </div>
    <div class="form-group">
        <?= $this->formElement($form->get('submit')); ?>
    </div>
        
        <?= $this->form()->closeTag(); ?>
</div>   
</div>
