<!DOCTYPE html>
<!-- saved from url=(0026)https://www.evtechnote.us/ -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Home</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--meta name="apple-mobile-web-app-capable" content="yes"-->
    <link href="/css/styles.css" type="text/css" rel="stylesheet">
    <link href="/css/nhp.css" type="text/css" rel="stylesheet">
    <!-- development version, includes helpful console warnings -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="/js/tinymce/tinymce.min.js" referrerpolicy="origin"></script>
<!--
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=a6a0g2hrxjm58bb5cysjzf6jgugbqf7l9u3m8hfjkdj3mkg7"></script> 
-->
    <script src="/js/nhpress.js"></script>
    <script>tinymce.init({selector: '#wordage-edit-textarea',
			plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed linkchecker a11ychecker tinymcespellchecker permanentpen powerpaste advtable advcode editimage tinycomments tableofcontents footnotes mergetags autocorrect typography inlinecss',
      			toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
      			tinycomments_mode: 'embedded',
      			tinycomments_author: 'Author name',
      mergetags_list: [
        { value: 'First.Name', title: 'First Name' },
        { value: 'Email', title: 'Email' },
      ]
    });
	</script>
 </head>
<body class="body_class">
    <div id="main-bar" class="evtechnote-color-1">
	<div>
    	    <ul>
	        <?php echo print_r($this->layout()->site_toolbar,true) ?>
	        <?php echo print_r($this->layout()->user_toolbar,true) ?>
            </ul>
	</div>
	<div id="issue_date">
            <div style="color:magenta;font-family:Ariel;font-style:bold;font-size:24pt;">&nbsp;&nbsp;evanwilliamsconsulting.com</div>
	</div>
    </div>
    <div id="main-header">
      <div id="lightbulb"><a href="/"><img src="/img/lightbulb.jpg"/></a></div>
      <div id="main-toolbar" class="evtechnote-color-1">
	      <?php echo print_r($this->layout()->action_toolbar,true) ?>
      </div>
      <div id="content" class="evtechnote-color-2">
		<?php echo $this->content; ?>
      </div>	
    </div>
    <div id="main-footer" class="evtechnote-color-1">
	<div id="dialog_box">
	</div>
	<div id="textedit" class="editbox">
	</div>
    	<div id="footer_text">
		<span class="white">© <?php echo date("Y") ?> Evan Williams Consulting, LLC</span>
    	</div>
    </div>
</body>
</html>
