<div id="<?php echo $this->wordageid; ?>" class="wordage-edit-text"> 
	<!-- span onclick="closeEditWordage();">Save</span -->
	<form method="post" action="/wordage/save?id=<?php echo $this->id; ?>&from=<?php echo $this->from; ?>">
	<input type="text" id="title" name="title" value="<?php echo $this->title;?>">
    	<textarea id="wordage-edit-textarea" rows=20 cols=60 name="wordage"><?php echo $this->content; ?></textarea>
	<input type="submit" id="Save" name="Save"/>
	</form>
</div>
