<div id="picture-div" class="width800 viewcolor">
	<h2><?php echo $this->title; ?></h2>
    <a href="/picture/edit?id=<?php echo $this->id;?>&from=picture">Edit</a>
    <h2>Picture - <?php echo $this->title; ?></h2>
    <div class="picture-item-caption">
        <span><?php echo $this->caption;?></span>
	<br />
        <span><?php echo $this->original;?></span>
    </div>
    <div onclick="clickPictureItem('picture-<?php echo $this->id;?>')">
    	<span><img src="<?php echo $this->picture; ?>" width=¨<?php echo $this->width; ?>¨ height=¨<?php echo $this->height; ?>¨></span>
    </div>
    <form method="post" action="/picture/resize?id=<?php echo $this->id; ?>&from=<?php echo $this->from; ?>">
	<label>Picture Width</label>
	<input id="picture_width" name="picture_width" type="text" value="<?php echo $this->resize_width; ?>">
	<label>Picture Height</label>
	<input id="picture_height" name="picture_height" type="text" value="<?php echo $this->resize_height; ?>">
    	<input id="picture_resize" name="picture_resize" value="Resize" type="submit"/>
    </form>
    <form enctype="multipart/form-data" method="post" action="/picture/upload?id=<?php echo $this->id; ?>&from=<?php echo $this->from; ?>">
	<input type="hidden" name="MAX_FILE_SIZE" value="10000000" />
	<select id="subfolder" name="subfolder">
	<?php
		$i = 1;
		foreach ($this->image_folders as $key => $folder)
		{
			echo "<option value='";
			echo $i;
			echo "'>";
			echo $folder;
			echo "</option>";
			$i += 1;
		}
	?>
	</select>
	<input type="file" id="myFile" name="filename">
        <input id="picture_upload" name="picture_upload" value="Upload" type="submit">
    </form>
</div>
